# -*- coding: utf-8 -*-
# Generated by Django 1.10.9 on 2018-02-22 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanti', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactno',
            field=models.IntegerField(default=1235),
            preserve_default=False,
        ),
    ]
